config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: [:ingredient_id] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true

  default_scope { order(name: :asc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @doses = @cocktail.doses
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail)
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def cocktail_params
    params.require(:cocktail).permit(:name, :ingredient, :description, :dose)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="form-actions" class ="btn btn-primary">
    <%= f.button :submit %>
  </div>
<%end%>

app/views/cocktails/edit.html.erb
<h1>Edit your cocktail:</h1>
<%=render 'form', cocktail: @cocktail %>

app/views/cocktails/index.html.erb
<div class = "background">

  <div class="banner">
    <div class="banner-content">
      <h1>Cocktails Menue</h1>
      <p>Create your own cocktails</p>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-xs-12 col-sm-3">
          <%= link_to cocktail_path(cocktail) do%>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://preview.ibb.co/hST64f/alcoholic-beverage-beverage-citrus-1232152-1.jpg');">
            <div class="card-category"><%= cocktail.name %></div>
            <div class="card-description">
              <p>Very cool city, the best</p>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= link_to "Add a new cocktail", new_cocktail_path, class: "btn btn-danger" %>

app/views/cocktails/new.html.erb
<h1>New cocktails</h1>
<%=render 'form', cocktails: @cocktail%>
<%=link_to 'Back', cocktails_path%>

app/views/cocktails/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
</p>

<p>
  <strong>Description:</strong>
  <% @doses.each do |dose| %>
    <li ><%= dose.description %></li>
  <% end %>
</p>
<p>
  <strong>Ingredients:</strong>
  <% @doses.each do |dose| %>
    <li><%= dose.ingredient.name %><%= link_to 'Delete', dose_path(dose), method: :delete%></li>
  <% end %>
</p>
<%= link_to 'Doses', new_cocktail_dose_path(@cocktail)%>
<%= link_to 'Edit', edit_cocktail_path%>
<%= link_to 'Back', cocktails_path%>

app/views/doses/new.html.erb
<h1>New Dose</h1>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <div class="form-inputs">
   <%= f.input :description %>
   <%= f.association :ingredient, collection: Ingredient.all%>
  </div>
  <div class="form-actions" class="btn btn-danger">
   <%= f.button :submit %>
  </div>
<% end %>
<%=link_to 'Back', cocktails_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>
  </body>
</html>